### ISSUE TITLE
Redundant / incorrect kernel module check

### ISSUE THREAD

**Issue by laenion** [coreos/ignition-dracut#176]
On a minimal system we recently stumbled over the following lines when building the initrd:

https://github.com/coreos/ignition-dracut/blob/390779da2c5b7595882a8426e2c9ec9c073c6da4/dracut/30ignition/module-setup.sh#L87-L108

There is one logical error in this code: It tries to include the `qemu_fw_cfg` module by checking whether the kernel has been built with that module. However if this is true it does not mean that this module is actually present - e.g. on openSUSE the kernel modules are spread over multiple packages to avoid installing unnecessary components.

However I'm also wondering something completely different: What is this snippet good for at all?

The ignition module already declares a `depends()` on `qemu`. When looking at the _qemu_ module code we can see that it will - among other modules - do a `hostonly='' instmods qemu_fw_cfg` - so it will also include the module if it is there (but with correct checking).

Am I missing something, or can the listed lines just be removed as they are?

**Comment by jlebon** [comment]
So the stance on this changed a bit over time. It used to be that we hard required `qemu_fw_cfg`, and so we would simply check if it was built-in and otherwise `instmods -c` (that's https://github.com/coreos/ignition-dracut/pull/28). Then it was changed to accommodate multi-arch, where it might not be supported as well (https://github.com/coreos/ignition-dracut/pull/49).

So I think you're right now that at this point this code isn't really useful. The original intent though was that on architectures which *do* support it, then we definitely do want to include the module because that's likely the only way for Ignition to get its config on QEMU (see https://github.com/coreos/ignition-dracut/pull/49#issuecomment-468773209). Just recently, the picture changed slightly with https://github.com/coreos/ignition/pull/905, but that only affects ppc64le and s390x; x86_64 and aarch64 on QEMU still only supports qemu_fw_cfg.

I think we could change this code to check for the architecture and make it a hard requirement (built-in or as a module) based on that.

Or for your use case are you not planning to support qemu_fw_cfg at all?

**Comment by laenion** [comment]
Thanks for the explanation, I didn't think about the case where the driver is part of the kernel.

So to repeat it in my own words:
* The default behavior would be that the kernel will include the module if it is available. If it isn't, it will just skip it silently.
* The `30ignition-dracut` code enforces that the module will be included in any case if the system would be able to do so. If that fails, the initrd creation will fail with an error message.

The only scenario I can think of where this difference matters is when kernel was compiled with `qemu_fw_cfg` as a module, but the module is not installed (so exactly the case where we have seen this).

> Or for your use case are you not planning to support qemu_fw_cfg at all?

That depends a bit - for our general purpose images we are also supporting qemu of course.
But when thinking about embedded devices for example you will want to keep to overhead minimal. Unused modules would be the first candidate to remove, so I think we have a different use case here...

Even if the system includes no platform specific driver it's still possible to configure it using `ignition.config.url`.

**Comment by jlebon** [comment]
> That depends a bit - for our general purpose images we are also supporting qemu of course.
But when thinking about embedded devices for example you will want to keep to overhead minimal. Unused modules would be the first candidate to remove, so I think we have a different use case here...

Thanks, I think that's a convincing argument. I opened https://github.com/coreos/ignition-dracut/pull/178.
